### ISSUE TITLE
option '-d, --devtool <value>' argument missing

### ISSUE THREAD

**Issue by lincy-NY** [khno/react-hello-world#2]
控制台里执行.\node_modules\.bin\webpack -d 报这个错是啥问题？mac上win上都是。

**Comment by xxxsf** [comment]
能否描述详细点？执行了什么，出现这个？

**Comment by xxxsf** [comment]
可以截图发上来看下

**Comment by lincy-NY** [comment]
helloworld的第四步，建完webpack.config.js然后写了个index.jsx，然后执行 ./node_modules/.bin/webpack -d
![image](https://user-images.githubusercontent.com/65845715/103897401-777da300-512e-11eb-9ad7-0242803a3c60.png)

**Comment by peiyumo** [comment]
webpack -d 报错，是缺少参数，后面加上“source-map” 或其他可用值（devtool属性的值）

**Comment by peiyumo** [comment]
webpack 有些参数是过时了么， npm run build 里的-p 参数好像一直都不存在 ？

**Comment by peiyumo** [comment]
webpack 有些参数是过时了么， npm run build 里的-p 参数好像一直都不存在 ？ @allan2coder 

抱歉可能是webpack-cli版本问题，用拉取的工程初始化webpack后，webpack --help 可以找到-p选项
